### PR TITLE
[JENKINS-30965] Add missing config.jelly for googleUserInfo.

### PR DESCRIPTION
**Pull request by Vlatombe**
https://issues.jenkins-ci.org/browse/JENKINS-30965

Prevents an error showing in the user configuration page.

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
:bee:

**Comment by jtnord** [comment]
doesn't this need to include some other pages so you can configure the users token etc?

If this is included from the main descriptor then I would expect that descriptor should check that the actual descriptor has a valid config page and not try to render the page if that is the case.

Note I don;t see any changes in the code that would have caused this to regressed for an upgrade of the plugin (as in the report)

**Comment by Vlatombe** [comment]
Yes I think this has never worked.

**Comment by Vlatombe** [comment]
@reviewbybees done

**Pull request merged**
