### PR TITLE
Allow multiple domains for jenkins. 

### PR DESCRIPTION
**Pull request by darashenka**
Redirect-URL should come from the current request

### CODE REVIEW

**Comment by haidaraM** [comment]
Any new on this PR ?

**Comment by iamhsa** [comment]
Any news ?

**Comment by darashenka** [comment]
@Vlatombe  please merge it

**Comment by Vlatombe** [comment]
Thank you for pinging me, I didn't get the previous notifications.

**Comment by cawka** [comment]
This PR has completely broken login capability in our system. We use jenkins behind a few proxies and so far we didn't have any need to preserve the URL, as redirect_url came from the configuration.   Can you at least add a configuration option to select where URL should be pulled?  Our setup cannot be the only one that is very negatively (and completely unexpectedly) affected by this change

**Pull request merged**
